# fly.toml app configuration file generated for rewind-api on 2026-01-11T18:49:03+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rewind-api'
primary_region = 'cdg'

[build]

[env]
  REWIND_DATABASE_URL = "sqlite:/data/rewind.db?mode=rwc"
  REWIND_SERVER_ADDRESS = "0.0.0.0:8080"
  REWIND_S3_GRIB_BUCKET = "rewind-gribs"
  REWIND_S3_RASTER_BUCKET = "rewind-wind-rasters"
  REWIND_S3_PATHS_BUCKET = "rewind-race-paths"
  REWIND_S3_ENDPOINT = "https://s3.eu-west-3.amazonaws.com"
  REWIND_S3_REGION = "eu-west-3"
  REWIND_EMAIL_FROM = "rewind@milox.dev"

[mounts]
  source = "rewind_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '30s'
    timeout = '5s'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
